#!/bin/bash

echo "🔍 Analyzing rpId Difference Between Registration and Authentication"
echo "=================================================================="
echo ""
echo "📋 Problem identified:"
echo "   ✅ FIDO Registration: rpId = 'nip.io' (correct)"
echo "   ❌ FIDO Authentication: rpId = 'wso2is' (incorrect)"
echo ""
echo "🔧 Root Cause Analysis:"
echo ""
echo "1. FIDO Registration uses:"
echo "   - Global configuration from deployment-aws.toml"
echo "   - authentication.fido2.app_id = 'fido.18.143.154.126.nip.io'"
echo "   - This is why registration works correctly"
echo ""
echo "2. FIDO Authentication uses:"
echo "   - Service Provider specific configuration"
echo "   - Stored in WSO2 IS database"
echo "   - Service Provider 'FIDO_POC_App' still has rpId = 'wso2is'"
echo "   - This is why authentication fails"
echo ""
echo "🎯 Solution:"
echo "   Update Service Provider configuration in WSO2 IS Console"
echo ""
echo "🚀 Steps to fix:"
echo ""
echo "1. Access WSO2 IS Console:"
echo "   https://wso2.18.143.154.126.nip.io:9443/carbon"
echo "   Username: admin"
echo "   Password: admin"
echo ""
echo "2. Navigate to Service Provider:"
echo "   - Applications > List"
echo "   - Find 'FIDO_POC_App'"
echo "   - Click Edit"
echo ""
echo "3. Update FIDO2 Configuration:"
echo "   - Relying Party ID: fido.18.143.154.126.nip.io"
echo "   - App ID: https://fido.18.143.154.126.nip.io"
echo "   - Trusted Origins:"
echo "     - https://fido.18.143.154.126.nip.io"
echo "     - https://wso2.18.143.154.126.nip.io"
echo ""
echo "4. Save and test"
echo ""
echo "📝 Why this happens:"
echo "   - WSO2 IS has two levels of FIDO2 configuration:"
echo "     * Global level (deployment-aws.toml) - used for registration"
echo "     * Service Provider level (database) - used for authentication"
echo "   - Service Provider level overrides global level"
echo "   - Your Service Provider still has old 'wso2is' configuration"
echo ""
echo "✅ After fix:"
echo "   - Registration: rpId = 'fido.18.143.154.126.nip.io' ✅"
echo "   - Authentication: rpId = 'fido.18.143.154.126.nip.io' ✅"
echo "   - Both will work consistently"


