#!/bin/bash

echo "🔧 Manual WSO2 IS Configuration Guide"
echo "===================================="
echo ""
echo "📋 Problem: WSO2 IS returns rpId: 'wso2is' instead of nip.io domain"
echo "🎯 Solution: Use official WSO2 IS image and configure manually"
echo ""
echo "🚀 Steps to fix rpId issue:"
echo ""
echo "1. Update docker-compose.yml to use official WSO2 IS:"
echo "   image: wso2/wso2is:7.1.0"
echo ""
echo "2. Start services:"
echo "   docker-compose up -d"
echo ""
echo "3. Access WSO2 IS Console:"
echo "   https://wso2.18.143.154.126.nip.io:9443/carbon"
echo "   Username: admin"
echo "   Password: admin"
echo ""
echo "4. Create Service Provider:"
echo "   - Go to Applications > Create"
echo "   - Name: FIDO_POC_App"
echo "   - Description: FIDO Demo Application"
echo ""
echo "5. Configure OAuth2:"
echo "   - Go to Protocol tab"
echo "   - OAuth Version: 2.0"
echo "   - Grant Types: Authorization Code, Refresh Token"
echo "   - Callback URL: https://fido.18.143.154.126.nip.io/oauth2/code/wso2"
echo "   - Allowed Origins: https://fido.18.143.154.126.nip.io"
echo ""
echo "6. Configure FIDO2:"
echo "   - Go to FIDO2 tab"
echo "   - Enable FIDO2"
echo "   - Relying Party ID: fido.18.143.154.126.nip.io"
echo "   - App ID: https://fido.18.143.154.126.nip.io"
echo "   - Trusted Origins:"
echo "     - https://fido.18.143.154.126.nip.io"
echo "     - https://wso2.18.143.154.126.nip.io"
echo ""
echo "7. Save and test:"
echo "   - Access: https://fido.18.143.154.126.nip.io"
echo "   - Try FIDO authentication"
echo "   - Should now use correct rpId"
echo ""
echo "🎯 Expected result:"
echo "   ✅ rpId should be 'fido.18.143.154.126.nip.io'"
echo "   ✅ No more 'wso2is' rpId in response"
echo "   ✅ WebAuthn authentication should work"
echo ""
echo "📝 Note: This approach gives you:"
echo "   ✅ Clean WSO2 IS instance"
echo "   ✅ Full control over configuration"
echo "   ✅ Correct rpId for FIDO2"
echo "   ⚠️  Requires manual setup"


