#!/bin/bash

echo "✅ FIDO App Updated with Final Client Credentials"
echo "=================================================="
echo ""
echo "📦 Image details:"
echo "   ✅ Repository: ngoduyanh/fido-app"
echo "   ✅ Tag: latest"
echo "   ✅ Platforms: linux/amd64, linux/arm64"
echo "   ✅ Docker Hub URL: https://hub.docker.com/r/ngoduyanh/fido-app"
echo ""
echo "🔧 Final configuration:"
echo "   ✅ Domain: https://anhngo.site"
echo "   ✅ WSO2 IS URL: https://ndanh.site"
echo "   ✅ NEW Client ID: rIiIVlyPm0ziDybjCmw3R7n2FUga"
echo "   ✅ NEW Client Secret: poeC1OVJLgssbBmAyvIx_ib3e1YXlaz_xoV7HV9m1Boa"
echo "   ✅ FIDO RP ID: anhngo.site"
echo "   ✅ FIDO App ID: https://anhngo.site"
echo "   ✅ Trusted Origins: ndanh.site, anhngo.site"
echo ""
echo "📝 Files updated:"
echo "   ✅ application.properties - Backend client credentials"
echo "   ✅ application-docker.properties - Docker client credentials"
echo "   ✅ app.js - Frontend client credentials"
echo "   ✅ success.html - Frontend client credentials"
echo "   ✅ FIDO app image rebuilt and pushed"
echo ""
echo "🚀 To run FIDO app:"
echo "   docker-compose -f docker-compose-fido-only.yml up -d"
echo ""
echo "📝 Requirements:"
echo "   - WSO2 IS must be running on https://ndanh.site"
echo "   - WSO2 IS must have Service Provider 'FIDO_POC_App' configured with:"
echo "     - OAuth2 Client ID: rIiIVlyPm0ziDybjCmw3R7n2FUga"
echo "     - OAuth2 Client Secret: poeC1OVJLgssbBmAyvIx_ib3e1YXlaz_xoV7HV9m1Boa"
echo "     - Callback URL: https://anhngo.site/oauth2/code/wso2"
echo "     - Relying Party ID: anhngo.site"
echo "     - App ID: https://anhngo.site"
echo "     - Trusted Origins: ndanh.site, anhngo.site"
echo ""
echo "🎯 Expected behavior:"
echo "   ✅ FIDO app accessible at https://anhngo.site"
echo "   ✅ OAuth2 authentication works with new credentials"
echo "   ✅ Native authentication works"
echo "   ✅ FIDO registration and authentication work"
echo ""
echo "✅ Ready for deployment with final client credentials!"

