#!/bin/bash

echo "🔧 Configuring FIDO2/Passkey Authenticator in WSO2 IS"
echo "====================================================="
echo ""
echo "📋 Problem identified:"
echo "   ❌ Only 'Username & Password' authenticator available"
echo "   ❌ No 'Passkey' authenticator in response"
echo "   ❌ FIDO2/Passkey authenticator not configured in WSO2 IS"
echo ""
echo "🚀 Steps to enable FIDO2/Passkey authenticator:"
echo ""
echo "1. Access WSO2 IS Console:"
echo "   https://ndanh.site:9443/carbon"
echo "   Username: admin"
echo "   Password: admin"
echo ""
echo "2. Enable FIDO2 Authenticator:"
echo "   - Go to 'Identity Providers' > 'Local'"
echo "   - Click 'Federated Authenticators'"
echo "   - Find 'FIDO2' or 'Passkey' authenticator"
echo "   - Enable it"
echo ""
echo "3. Alternative path - Authentication Methods:"
echo "   - Go to 'Authentication' > 'Authentication Methods'"
echo "   - Look for 'FIDO2' or 'Passkey'"
echo "   - Enable it"
echo ""
echo "4. Configure FIDO2 Settings:"
echo "   - Relying Party ID: fido.18.143.154.126.nip.io"
echo "   - App ID: https://fido.18.143.154.126.nip.io"
echo "   - Trusted Origins:"
echo "     - https://fido.18.143.154.126.nip.io"
echo "     - https://ndanh.site"
echo ""
echo "5. Update Service Provider:"
echo "   - Go to 'Applications' > 'List'"
echo "   - Find 'FIDO_POC_App'"
echo "   - Click 'Edit'"
echo "   - Go to 'Authentication' tab"
echo "   - Add 'FIDO2' authenticator to authentication steps"
echo "   - Set it as required or optional"
echo ""
echo "6. Test the configuration:"
echo "   - Access: https://fido.18.143.154.126.nip.io"
echo "   - Try native authentication"
echo "   - Should now see 'Passkey' option"
echo ""
echo "🔍 Expected result after configuration:"
echo "   ✅ Response should include 'Passkey' authenticator"
echo "   ✅ FIDO2/WebAuthn authentication should work"
echo "   ✅ Both 'Username & Password' and 'Passkey' options available"
echo ""
echo "📝 Alternative approach - Check WSO2 IS version:"
echo "   - WSO2 IS 7.1.0 should have FIDO2 support"
echo "   - If not available, may need to install FIDO2 connector"
echo "   - Check 'Connectors' section in WSO2 IS Console"
echo ""
echo "🎯 This will enable Passkey authentication option!"

