#!/bin/bash

echo "✅ FIDO App Updated with rpId Fix"
echo "=================================="
echo ""
echo "🔧 Changes made:"
echo "   ✅ Added FIDO_RELYING_PARTY environment variable"
echo "   ✅ Updated NativeAuthService to process challengeData"
echo "   ✅ Added base64 decode/encode logic for challengeData"
echo "   ✅ Replace rpId with configured relying party (anhngo.site)"
echo ""
echo "📦 Image details:"
echo "   ✅ Repository: ngoduyanh/fido-app"
echo "   ✅ Tag: latest"
echo "   ✅ Platforms: linux/amd64, linux/arm64"
echo "   ✅ Docker Hub URL: https://hub.docker.com/r/ngoduyanh/fido-app"
echo ""
echo "🔧 How it works:"
echo "   1. WSO2 IS returns challengeData with rpId from its configuration"
echo "   2. FIDO app decodes the base64 challengeData"
echo "   3. Replaces rpId with our configured relying party (anhngo.site)"
echo "   4. Encodes back to base64 and returns to client"
echo "   5. Client receives challengeData with correct rpId"
echo ""
echo "🎯 Expected behavior:"
echo "   ✅ No more 'different relying party' errors"
echo "   ✅ FIDO authentication works with correct rpId"
echo "   ✅ ChallengeData contains anhngo.site as rpId"
echo ""
echo "🚀 To run updated FIDO app:"
echo "   docker-compose -f docker-compose-fido-only.yml up -d"
echo ""
echo "📝 Logs to check:"
echo "   - 'Original challengeData: ...' - shows original rpId from WSO2"
echo "   - 'Replaced rpId with: anhngo.site' - confirms replacement"
echo "   - 'Updated challengeData: ...' - shows final result"
echo ""
echo "✅ FIDO app updated with rpId fix and pushed successfully!"


