#!/bin/bash

echo "✅ FIDO App Domain Changed to anhngo.site"
echo "========================================"
echo ""
echo "📦 Image details:"
echo "   ✅ Repository: ngoduyanh/fido-app"
echo "   ✅ Tag: latest"
echo "   ✅ Platforms: linux/amd64, linux/arm64"
echo "   ✅ Docker Hub URL: https://hub.docker.com/r/ngoduyanh/fido-app"
echo ""
echo "🔧 Domain changes applied:"
echo "   ✅ OLD Domain: https://fido.18.143.154.126.nip.io"
echo "   ✅ NEW Domain: https://anhngo.site"
echo "   ✅ WSO2 IS URL: https://ndanh.site (unchanged)"
echo "   ✅ Client ID: IfaLKDbx1ybAmBmxvjuMUEP8vaQa (unchanged)"
echo "   ✅ Client Secret: PMlKYi_HFX3c0yTogdNUcrV4jeFsfYax3llko8DRlhYa (unchanged)"
echo ""
echo "📝 Files updated:"
echo "   ✅ application.properties - OAuth redirect URI and FIDO config"
echo "   ✅ application-docker.properties - OAuth redirect URI and FIDO config"
echo "   ✅ docker-compose-fido-only.yml - Environment variables"
echo "   ✅ app.js - OAuth redirect URI"
echo "   ✅ FIDO app image rebuilt and pushed"
echo ""
echo "🚀 To run FIDO app:"
echo "   docker-compose -f docker-compose-fido-only.yml up -d"
echo ""
echo "📝 Requirements:"
echo "   - WSO2 IS must be running on https://ndanh.site"
echo "   - WSO2 IS must have Service Provider 'FIDO_POC_App' configured with:"
echo "     - OAuth2 Client ID: IfaLKDbx1ybAmBmxvjuMUEP8vaQa"
echo "     - OAuth2 Client Secret: PMlKYi_HFX3c0yTogdNUcrV4jeFsfYax3llko8DRlhYa"
echo "     - Callback URL: https://anhngo.site/oauth2/code/wso2"
echo "     - Relying Party ID: anhngo.site"
echo "     - App ID: https://anhngo.site"
echo "     - Trusted Origins: ndanh.site, anhngo.site"
echo ""
echo "🎯 Expected behavior:"
echo "   ✅ FIDO app accessible at https://anhngo.site"
echo "   ✅ OAuth2 authentication works with new domain"
echo "   ✅ Native authentication works"
echo "   ✅ FIDO registration and authentication work"
echo ""
echo "✅ Ready for deployment with new domain anhngo.site!"

