#!/bin/bash

echo "✅ FIDO App Updated with New Client Credentials"
echo "=============================================="
echo ""
echo "🔧 Updated credentials:"
echo "   ✅ Client ID: iNd9bRH7tknjJYOtnijxEt39LDUa"
echo "   ✅ Client Secret: Ih6EQjdDppzw9_v5nav9CGziBNrZ7R4iC9MfyJVLL8Ya"
echo ""
echo "📁 Files updated:"
echo "   ✅ application.properties"
echo "   ✅ application-docker.properties"
echo "   ✅ app.js (frontend JavaScript)"
echo "   ✅ success.html (frontend HTML)"
echo "   ✅ docker-compose-fido-only.yml"
echo ""
echo "📦 Image details:"
echo "   ✅ Repository: ngoduyanh/fido-app"
echo "   ✅ Tag: latest"
echo "   ✅ Platforms: linux/amd64, linux/arm64"
echo "   ✅ Docker Hub URL: https://hub.docker.com/r/ngoduyanh/fido-app"
echo ""
echo "🔧 Current configuration:"
echo "   ✅ Domain: https://anhngo.site"
echo "   ✅ WSO2 IS URL: https://ndanh.site"
echo "   ✅ Client ID: iNd9bRH7tknjJYOtnijxEt39LDUa"
echo "   ✅ Client Secret: Ih6EQjdDppzw9_v5nav9CGziBNrZ7R4iC9MfyJVLL8Ya"
echo "   ✅ FIDO RP ID: anhngo.site"
echo "   ✅ FIDO App ID: https://anhngo.site"
echo "   ✅ Trusted Origins: ndanh.site, anhngo.site"
echo ""
echo "🚀 To run FIDO app:"
echo "   docker-compose -f docker-compose-fido-only.yml up -d"
echo ""
echo "📝 Requirements:"
echo "   - WSO2 IS must be running on https://ndanh.site"
echo "   - WSO2 IS must have Service Provider 'FIDO_POC_App' configured with:"
echo "     - OAuth2 Client ID: iNd9bRH7tknjJYOtnijxEt39LDUa"
echo "     - OAuth2 Client Secret: Ih6EQjdDppzw9_v5nav9CGziBNrZ7R4iC9MfyJVLL8Ya"
echo "     - Callback URL: https://anhngo.site/oauth2/code/wso2"
echo "     - Relying Party ID: anhngo.site"
echo "     - App ID: https://anhngo.site"
echo "     - Trusted Origins: ndanh.site, anhngo.site"
echo ""
echo "🎯 Expected behavior:"
echo "   ✅ FIDO app accessible at https://anhngo.site"
echo "   ✅ OAuth2 authentication works with new credentials"
echo "   ✅ Native authentication works"
echo "   ✅ FIDO registration and authentication work"
echo "   ✅ rpId fix applied (challengeData processed)"
echo ""
echo "✅ FIDO app updated with new client credentials and pushed successfully!"