#!/bin/bash

echo "✅ FIDO App Updated with New Client Credentials"
echo "=============================================="
echo ""
echo "📦 Image details:"
echo "   ✅ Repository: ngoduyanh/fido-app"
echo "   ✅ Tag: latest"
echo "   ✅ Platforms: linux/amd64, linux/arm64"
echo "   ✅ Docker Hub URL: https://hub.docker.com/r/ngoduyanh/fido-app"
echo ""
echo "🔧 Updated configuration:"
echo "   ✅ WSO2 IS URL: https://ndanh.site"
echo "   ✅ NEW Client ID: kfei09g7ucf_yf0e2fSGMPgTB8Ya"
echo "   ✅ NEW Client Secret: xn1HN1YHP6vQ9ygAuGECuSZzAtu7KAbOvpzQuDIbYBwa"
echo "   ✅ FIDO RP ID: fido.18.143.154.126.nip.io"
echo "   ✅ FIDO App ID: https://fido.18.143.154.126.nip.io"
echo "   ✅ Trusted Origins: ndanh.site, fido.18.143.154.126.nip.io"
echo ""
echo "🚀 To run FIDO app:"
echo "   docker-compose -f docker-compose-fido-only.yml up -d"
echo ""
echo "📝 Requirements:"
echo "   - WSO2 IS must be running on https://ndanh.site"
echo "   - WSO2 IS must have Service Provider 'FIDO_POC_App' configured with:"
echo "     - OAuth2 Client ID: kfei09g7ucf_yf0e2fSGMPgTB8Ya"
echo "     - OAuth2 Client Secret: xn1HN1YHP6vQ9ygAuGECuSZzAtu7KAbOvpzQuDIbYBwa"
echo "     - Callback URL: https://fido.18.143.154.126.nip.io/oauth2/code/wso2"
echo "     - Relying Party ID: fido.18.143.154.126.nip.io"
echo "     - App ID: https://fido.18.143.154.126.nip.io"
echo "     - Trusted Origins: ndanh.site, fido.18.143.154.126.nip.io"
echo ""
echo "🎯 Ready for deployment!"
echo "   ✅ Image built and pushed successfully"
echo "   ✅ Multi-platform support (AMD64/ARM64)"
echo "   ✅ Updated client credentials"
echo "   ✅ Ready to run on any server"

