#!/bin/bash

echo "🔧 Fixing rpId in WSO2 IS Service Provider Configuration"
echo "========================================================"
echo ""
echo "📋 Problem identified:"
echo "   ❌ rpId in challengeData is still 'wso2is'"
echo "   ✅ Need to update Service Provider configuration"
echo ""
echo "🚀 Step-by-step fix:"
echo ""
echo "1. Start WSO2 IS container:"
echo "   docker-compose up -d wso2is"
echo ""
echo "2. Wait for WSO2 IS to start (2-3 minutes):"
echo "   docker-compose logs -f wso2is"
echo ""
echo "3. Access WSO2 IS Console:"
echo "   https://wso2.18.143.154.126.nip.io:9443/carbon"
echo "   Username: admin"
echo "   Password: admin"
echo ""
echo "4. Navigate to Service Provider:"
echo "   - Click 'Applications' in left menu"
echo "   - Click 'List'"
echo "   - Find 'FIDO_POC_App'"
echo "   - Click 'Edit' (pencil icon)"
echo ""
echo "5. Update FIDO2 Configuration:"
echo "   - Click 'FIDO2' tab"
echo "   - Update 'Relying Party ID': fido.18.143.154.126.nip.io"
echo "   - Update 'App ID': https://fido.18.143.154.126.nip.io"
echo "   - Update 'Trusted Origins':"
echo "     - https://fido.18.143.154.126.nip.io"
echo "     - https://wso2.18.143.154.126.nip.io"
echo "   - Click 'Update' button"
echo ""
echo "6. Test the fix:"
echo "   - Access: https://fido.18.143.154.126.nip.io"
echo "   - Try native authentication"
echo "   - Check browser console for new rpId value"
echo ""
echo "🎯 Expected result after fix:"
echo "   ✅ rpId should be 'fido.18.143.154.126.nip.io'"
echo "   ✅ No more 'wso2is' rpId in challengeData"
echo "   ✅ WebAuthn authentication should work"
echo ""
echo "📝 Current issue:"
echo "   - challengeData shows: {\"rpId\":\"wso2is\"}"
echo "   - Should show: {\"rpId\":\"fido.18.143.154.126.nip.io\"}"
echo ""
echo "🔍 To verify the fix:"
echo "   - After updating Service Provider"
echo "   - Call native auth init API again"
echo "   - Decode challengeData and check rpId value"
echo ""
echo "✅ This will fix the rpId issue permanently!"


