#!/bin/bash

echo "🔧 Fixing rpId in WSO2 IS 7.1 - Correct Navigation"
echo "================================================="
echo ""
echo "📋 WSO2 IS 7.1 has different UI structure:"
echo "   - Applications = Service Providers"
echo "   - Different menu structure"
echo ""
echo "🚀 Correct steps for WSO2 IS 7.1:"
echo ""
echo "1. Start WSO2 IS container:"
echo "   docker-compose up -d wso2is"
echo ""
echo "2. Wait for WSO2 IS to start (2-3 minutes):"
echo "   docker-compose logs -f wso2is"
echo ""
echo "3. Access WSO2 IS Console:"
echo "   https://wso2.18.143.154.126.nip.io:9443/carbon"
echo "   Username: admin"
echo "   Password: admin"
echo ""
echo "4. Navigate to Service Providers (WSO2 IS 7.1):"
echo "   - Look for 'Service Providers' in left menu"
echo "   - OR look for 'Applications' in left menu"
echo "   - OR look for 'Identity' section"
echo "   - Click on 'Service Providers' or 'Applications'"
echo ""
echo "5. Find and Edit Service Provider:"
echo "   - Look for 'FIDO_POC_App' in the list"
echo "   - Click 'Edit' or pencil icon"
echo "   - OR click on the service provider name"
echo ""
echo "6. Update FIDO2 Configuration:"
echo "   - Look for 'FIDO2' tab"
echo "   - OR look for 'FIDO' tab"
echo "   - OR look for 'WebAuthn' tab"
echo "   - Update 'Relying Party ID': fido.18.143.154.126.nip.io"
echo "   - Update 'App ID': https://fido.18.143.154.126.nip.io"
echo "   - Update 'Trusted Origins':"
echo "     - https://fido.18.143.154.126.nip.io"
echo "     - https://wso2.18.143.154.126.nip.io"
echo "   - Click 'Update' or 'Save' button"
echo ""
echo "7. Alternative navigation paths in WSO2 IS 7.1:"
echo "   - Main Menu > Identity > Service Providers"
echo "   - Main Menu > Applications"
echo "   - Left sidebar > Service Providers"
echo "   - Left sidebar > Applications"
echo ""
echo "8. Test the fix:"
echo "   - Access: https://fido.18.143.154.126.nip.io"
echo "   - Try native authentication"
echo "   - Check browser console for new rpId value"
echo ""
echo "🎯 Expected result after fix:"
echo "   ✅ rpId should be 'fido.18.143.154.126.nip.io'"
echo "   ✅ No more 'wso2is' rpId in challengeData"
echo "   ✅ WebAuthn authentication should work"
echo ""
echo "📝 WSO2 IS 7.1 UI differences:"
echo "   - Service Providers instead of Applications"
echo "   - Different menu structure"
echo "   - FIDO2/WebAuthn configuration in different tabs"
echo ""
echo "🔍 If you can't find the menu:"
echo "   - Look for 'Identity' section"
echo "   - Look for 'Service Providers'"
echo "   - Look for 'Applications'"
echo "   - Check both left sidebar and main menu"


