#!/bin/bash

echo "🔧 Fixed Client Credentials Mismatch"
echo "===================================="
echo ""
echo "📋 Problem identified:"
echo "   ❌ Frontend JavaScript was using old client ID: jDsWosgzDKXGRUPHXhLnlm1wQQ8a"
echo "   ❌ Backend was using new client ID: kfei09g7ucf_yf0e2fSGMPgTB8Ya"
echo "   ❌ This caused 401 Unauthorized error"
echo ""
echo "✅ Solution applied:"
echo "   ✅ Updated app.js - WSO2_CLIENT_ID: kfei09g7ucf_yf0e2fSGMPgTB8Ya"
echo "   ✅ Updated app.js - WSO2_CLIENT_SECRET: xn1HN1YHP6vQ9ygAuGECuSZzAtu7KAbOvpzQuDIbYBwa"
echo "   ✅ Updated success.html - WSO2_CLIENT_ID: kfei09g7ucf_yf0e2fSGMPgTB8Ya"
echo "   ✅ Updated OAuth2 parameters in app.js"
echo "   ✅ FIDO app image rebuilt and pushed"
echo ""
echo "📦 Image details:"
echo "   ✅ Repository: ngoduyanh/fido-app"
echo "   ✅ Tag: latest"
echo "   ✅ Platforms: linux/amd64, linux/arm64"
echo "   ✅ Docker Hub URL: https://hub.docker.com/r/ngoduyanh/fido-app"
echo ""
echo "🚀 To test the fix:"
echo "   1. Pull latest image: docker-compose -f docker-compose-fido-only.yml pull"
echo "   2. Restart FIDO app: docker-compose -f docker-compose-fido-only.yml up -d"
echo "   3. Test native authentication:"
echo "      - Access: https://fido.18.143.154.126.nip.io"
echo "      - Try native authentication"
echo "      - Should no longer get 401 Unauthorized error"
echo ""
echo "🔧 Configuration now consistent:"
echo "   ✅ Backend: kfei09g7ucf_yf0e2fSGMPgTB8Ya"
echo "   ✅ Frontend: kfei09g7ucf_yf0e2fSGMPgTB8Ya"
echo "   ✅ WSO2 IS Service Provider must be configured with same credentials"
echo ""
echo "📝 Requirements:"
echo "   - WSO2 IS must have Service Provider 'FIDO_POC_App' with:"
echo "     - OAuth2 Client ID: kfei09g7ucf_yf0e2fSGMPgTB8Ya"
echo "     - OAuth2 Client Secret: xn1HN1YHP6vQ9ygAuGECuSZzAtu7KAbOvpzQuDIbYBwa"
echo "     - Callback URL: https://fido.18.143.154.126.nip.io/oauth2/code/wso2"
echo "     - Relying Party ID: fido.18.143.154.126.nip.io"
echo "     - App ID: https://fido.18.143.154.126.nip.io"
echo "     - Trusted Origins: ndanh.site, fido.18.143.154.126.nip.io"
echo ""
echo "🎯 Expected result:"
echo "   ✅ No more 401 Unauthorized error"
echo "   ✅ Native authentication should work"
echo "   ✅ FIDO registration and authentication should work"
echo ""
echo "✅ Client credentials mismatch fixed!"

