#!/bin/bash

echo "🔧 Testing Callback URL Fix"
echo "==========================="
echo ""
echo "📋 Problem identified:"
echo "   ❌ Callback URL mismatch: https://fido.18.143.154.126.nip.io:8080/oauth2/code/wso2"
echo "   ✅ Fixed to: https://fido.18.143.154.126.nip.io/oauth2/code/wso2"
echo ""
echo "🔧 Changes made:"
echo "   - Removed port :8080 from redirect-uri"
echo "   - Updated trusted origins to use proper domains"
echo "   - Fixed OAuth2 callback URL configuration"
echo ""
echo "🚀 To test the fix:"
echo "   1. Pull latest image: docker-compose pull"
echo "   2. Restart services: docker-compose up -d"
echo "   3. Test native authentication:"
echo "      - Access: https://fido.18.143.154.126.nip.io"
echo "      - Try native authentication flow"
echo "      - Should no longer get 'callback.not.match' error"
echo ""
echo "🔍 Expected behavior:"
echo "   - OAuth2 callback URL should match registered URL in WSO2 IS"
echo "   - Native authentication should work without errors"
echo "   - No more 'Invalid authentication request' errors"
echo ""
echo "✅ FIDO App image updated:"
echo "   - Repository: ngoduyanh/fido-app"
echo "   - Tag: latest"
echo "   - Fixed callback URL configuration"
echo ""
echo "🎉 Ready for testing with corrected OAuth2 callback!"