#!/bin/bash

echo "🔧 Testing Separate WSO2 IS and FIDO App Instances"
echo "=================================================="
echo ""
echo "📋 Configuration:"
echo "   ✅ WSO2 IS: https://ndanh.site:9443"
echo "   ✅ FIDO App: https://fido.18.143.154.126.nip.io"
echo "   ✅ FIDO App connects to external WSO2 IS"
echo ""
echo "🚀 To run FIDO app with separate WSO2 IS:"
echo ""
echo "1. Start FIDO app only:"
echo "   docker-compose -f docker-compose-fido-only.yml up -d"
echo ""
echo "2. Check FIDO app status:"
echo "   docker-compose -f docker-compose-fido-only.yml ps"
echo ""
echo "3. Check FIDO app logs:"
echo "   docker-compose -f docker-compose-fido-only.yml logs -f fido-app"
echo ""
echo "4. Test FIDO app:"
echo "   - Access: https://fido.18.143.154.126.nip.io"
echo "   - Try native authentication"
echo "   - Should connect to WSO2 IS at ndanh.site:9443"
echo ""
echo "🔧 Configuration files updated:"
echo "   ✅ application.properties - WSO2 IS URL updated"
echo "   ✅ application-docker.properties - WSO2 IS URL updated"
echo "   ✅ docker-compose-fido-only.yml - Standalone FIDO app"
echo "   ✅ FIDO app image rebuilt and pushed"
echo ""
echo "📝 Important notes:"
echo "   - WSO2 IS must be running on ndanh.site:9443"
echo "   - WSO2 IS must have correct Service Provider configuration"
echo "   - Service Provider 'FIDO_POC_App' must be configured with:"
echo "     - Relying Party ID: fido.18.143.154.126.nip.io"
echo "     - App ID: https://fido.18.143.154.126.nip.io"
echo "     - Trusted Origins: ndanh.site, fido.18.143.154.126.nip.io"
echo ""
echo "🎯 Expected behavior:"
echo "   ✅ FIDO app connects to external WSO2 IS"
echo "   ✅ Native authentication works"
echo "   ✅ FIDO registration and authentication work"
echo "   ✅ No more rpId issues"
echo ""
echo "✅ Ready to test separate instances setup!"

