#!/bin/bash

echo "🔧 Testing All Callback URL Fixes"
echo "=================================="
echo ""
echo "📋 Found and fixed callback URL issues:"
echo ""
echo "1. ✅ application-docker.properties:"
echo "   - wso2.is.oauth.redirect-uri=https://fido.18.143.154.126.nip.io/oauth2/code/wso2"
echo ""
echo "2. ✅ app.js (frontend):"
echo "   - redirect_uri: 'https://fido.18.143.154.126.nip.io/oauth2/code/wso2'"
echo ""
echo "3. ✅ Wso2Service.java (backend):"
echo "   - redirect_uri: 'https://fido.18.143.154.126.nip.io/oauth2/code/wso2'"
echo ""
echo "4. ✅ deployment-aws.toml (WSO2 IS):"
echo "   - CORS allowed_origins updated"
echo "   - FIDO2 trusted origins updated"
echo ""
echo "5. ✅ identity.xml (WSO2 IS):"
echo "   - FIDO2TrustedOrigins updated"
echo "   - AllowedOrigins updated"
echo ""
echo "🚀 To test all fixes:"
echo "   1. Pull latest images:"
echo "      docker-compose pull"
echo ""
echo "   2. Restart services:"
echo "      docker-compose up -d"
echo ""
echo "   3. Test native authentication:"
echo "      - Access: https://fido.18.143.154.126.nip.io"
echo "      - Try native authentication flow"
echo "      - Should work without callback URL errors"
echo ""
echo "🔍 Expected behavior:"
echo "   ✅ No more 'callback.not.match' errors"
echo "   ✅ No more 'Invalid authentication request' errors"
echo "   ✅ Native authentication should work smoothly"
echo "   ✅ OAuth2 callback URL matches registered URL in WSO2 IS"
echo ""
echo "📦 Updated Images:"
echo "   - FIDO App: ngoduyanh/fido-app:latest"
echo "   - WSO2 IS: ngoduyanh/wso2is-custom-permission-fixed:latest"
echo ""
echo "🎉 All callback URL configurations are now consistent!"


