#!/bin/bash

echo "🔧 Testing rpId Fix for WebAuthn Authentication"
echo "=============================================="
echo ""
echo "📋 Problem identified:"
echo "   ❌ rpId was 'localhost' causing WebAuthn security error"
echo "   ✅ Fixed FIDO2TrustedOrigins in identity.xml to use nip.io domains"
echo ""
echo "🔧 Changes made:"
echo "   - Updated FIDO2TrustedOrigins in identity.xml"
echo "   - Removed localhost origins"
echo "   - Added nip.io domains: fido.18.143.154.126.nip.io, wso2.18.143.154.126.nip.io"
echo "   - Rebuilt WSO2 IS image with updated configuration"
echo ""
echo "🚀 To test the rpId fix:"
echo "   1. Pull latest images:"
echo "      docker-compose pull"
echo ""
echo "   2. Restart services:"
echo "      docker-compose up -d"
echo ""
echo "   3. Test FIDO authentication:"
echo "      - Access: https://fido.18.143.154.126.nip.io"
echo "      - Try FIDO registration/authentication"
echo "      - Should no longer get 'rpId not a registrable domain' error"
echo ""
echo "🔍 Expected behavior:"
echo "   ✅ rpId should be 'fido.18.143.154.126.nip.io' instead of 'localhost'"
echo "   ✅ WebAuthn authentication should work without security errors"
echo "   ✅ No more 'relying party ID is not a registrable domain suffix' error"
echo "   ✅ FIDO2 authentication should work smoothly"
echo ""
echo "📦 Updated Images:"
echo "   - WSO2 IS: ngoduyanh/wso2is-custom-permission-fixed:latest"
echo "   - FIDO App: ngoduyanh/fido-app:latest"
echo ""
echo "🎯 This fix addresses:"
echo "   ✅ WebAuthn rpId domain validation"
echo "   ✅ FIDO2 trusted origins configuration"
echo "   ✅ Security error resolution"
echo ""
echo "🎉 Ready for testing with corrected rpId configuration!"