#!/bin/bash

echo "🔧 Testing Updated WSO2 IS URL (No Port)"
echo "========================================"
echo ""
echo "📋 Configuration updated:"
echo "   ✅ WSO2 IS URL: https://ndanh.site (no port)"
echo "   ✅ FIDO App URL: https://fido.18.143.154.126.nip.io"
echo "   ✅ FIDO App image rebuilt and pushed"
echo ""
echo "🚀 To test the updated configuration:"
echo ""
echo "1. Start FIDO app:"
echo "   docker-compose -f docker-compose-fido-only.yml up -d"
echo ""
echo "2. Check FIDO app status:"
echo "   docker-compose -f docker-compose-fido-only.yml ps"
echo ""
echo "3. Check FIDO app logs:"
echo "   docker-compose -f docker-compose-fido-only.yml logs -f fido-app"
echo ""
echo "4. Test FIDO app:"
echo "   - Access: https://fido.18.143.154.126.nip.io"
echo "   - Try native authentication"
echo "   - Should connect to WSO2 IS at https://ndanh.site"
echo ""
echo "🔧 Files updated:"
echo "   ✅ application.properties - WSO2 IS URL without port"
echo "   ✅ application-docker.properties - WSO2 IS URL without port"
echo "   ✅ docker-compose-fido-only.yml - WSO2 IS URL without port"
echo "   ✅ FIDO app image rebuilt and pushed"
echo ""
echo "📝 Important notes:"
echo "   - WSO2 IS must be running on https://ndanh.site"
echo "   - WSO2 IS must have correct Service Provider configuration"
echo "   - Service Provider 'FIDO_POC_App' must be configured with:"
echo "     - Relying Party ID: fido.18.143.154.126.nip.io"
echo "     - App ID: https://fido.18.143.154.126.nip.io"
echo "     - Trusted Origins: ndanh.site, fido.18.143.154.126.nip.io"
echo ""
echo "🎯 Expected behavior:"
echo "   ✅ FIDO app connects to WSO2 IS without port"
echo "   ✅ Native authentication works"
echo "   ✅ FIDO registration and authentication work"
echo "   ✅ No more rpId issues"
echo ""
echo "✅ Ready to test with updated WSO2 IS URL!"

