#!/bin/bash

echo "🔧 Testing New Client Credentials"
echo "================================="
echo ""
echo "📋 Client credentials updated:"
echo "   ✅ Client ID: N81A8coMfEHKflZU9SNjGzSvMywa"
echo "   ✅ Client Secret: 5E9hPBKv_VDC4Q3wqfUOrB7DFbxUtOzCpxtcipfhLdQa"
echo "   ✅ FIDO App image rebuilt and pushed"
echo ""
echo "🚀 To test with new client credentials:"
echo ""
echo "1. Start FIDO app:"
echo "   docker-compose -f docker-compose-fido-only.yml up -d"
echo ""
echo "2. Check FIDO app status:"
echo "   docker-compose -f docker-compose-fido-only.yml ps"
echo ""
echo "3. Check FIDO app logs:"
echo "   docker-compose -f docker-compose-fido-only.yml logs -f fido-app"
echo ""
echo "4. Test FIDO app:"
echo "   - Access: https://fido.18.143.154.126.nip.io"
echo "   - Try native authentication"
echo "   - Should use new client credentials"
echo ""
echo "🔧 Files updated:"
echo "   ✅ application.properties - New client credentials"
echo "   ✅ application-docker.properties - New client credentials"
echo "   ✅ FIDO app image rebuilt and pushed"
echo ""
echo "📝 Important notes:"
echo "   - WSO2 IS must have Service Provider with new client credentials"
echo "   - Service Provider 'FIDO_POC_App' must be configured with:"
echo "     - OAuth2 Client ID: N81A8coMfEHKflZU9SNjGzSvMywa"
echo "     - OAuth2 Client Secret: 5E9hPBKv_VDC4Q3wqfUOrB7DFbxUtOzCpxtcipfhLdQa"
echo "     - Callback URL: https://fido.18.143.154.126.nip.io/oauth2/code/wso2"
echo "     - Relying Party ID: fido.18.143.154.126.nip.io"
echo "     - App ID: https://fido.18.143.154.126.nip.io"
echo "     - Trusted Origins: ndanh.site, fido.18.143.154.126.nip.io"
echo ""
echo "🎯 Expected behavior:"
echo "   ✅ FIDO app uses new client credentials"
echo "   ✅ OAuth2 authentication works with new credentials"
echo "   ✅ Native authentication works"
echo "   ✅ FIDO registration and authentication work"
echo ""
echo "✅ Ready to test with new client credentials!"

