#!/bin/bash

echo "🎯 Testing Updated Custom WSO2 IS Image"
echo "======================================"
echo ""
echo "📋 What was updated:"
echo "   ✅ Copied all configs from your local WSO2 IS"
echo "   ✅ Updated deployment-aws.toml with nip.io domains"
echo "   ✅ Rebuilt custom WSO2 IS image with latest data"
echo "   ✅ Updated docker-compose.yml to use custom image"
echo ""
echo "🔧 Custom WSO2 IS Image Features:"
echo "   ✅ All your localhost WSO2 IS configurations"
echo "   ✅ Service Provider: FIDO_POC_App (pre-configured)"
echo "   ✅ OAuth2 Client: jDsWosgzDKXGRUPHXhLnlm1wQQ8a"
echo "   ✅ FIDO2 settings with nip.io domains"
echo "   ✅ CORS configuration for nip.io domains"
echo "   ✅ All your custom users and data"
echo ""
echo "📦 Images being used:"
echo "   - WSO2 IS: ngoduyanh/wso2is-custom-permission-fixed:latest"
echo "   - FIDO App: ngoduyanh/fido-app:latest"
echo ""
echo "🚀 To test with updated custom WSO2 IS:"
echo "   1. Pull latest images:"
echo "      docker-compose pull"
echo ""
echo "   2. Start services:"
echo "      docker-compose up -d"
echo ""
echo "   3. Access WSO2 IS Console:"
echo "      https://wso2.18.143.154.126.nip.io:9443/carbon"
echo "      Username: admin"
echo "      Password: admin"
echo ""
echo "   4. Test FIDO App:"
echo "      https://fido.18.143.154.126.nip.io"
echo "      - Should work with pre-configured Service Provider"
echo "      - No manual configuration needed"
echo ""
echo "🎉 Benefits of using custom WSO2 IS image:"
echo "   ✅ No manual configuration required"
echo "   ✅ All your localhost data preserved"
echo "   ✅ Service Provider already configured"
echo "   ✅ FIDO2 settings already set up"
echo "   ✅ Ready to use immediately"
echo ""
echo "🔍 Expected behavior:"
echo "   ✅ Native authentication should work without errors"
echo "   ✅ No callback URL mismatch errors"
echo "   ✅ FIDO registration and authentication should work"
echo "   ✅ All your custom configurations preserved"


