#!/bin/bash

echo "🔧 Updating Service Provider Configuration"
echo "=========================================="
echo ""
echo "📋 This script will update the Service Provider rpId in WSO2 IS"
echo "   from 'wso2is' to 'fido.18.143.154.126.nip.io'"
echo ""
echo "🚀 Steps to fix rpId in custom WSO2 IS image:"
echo ""
echo "1. Start WSO2 IS container:"
echo "   docker-compose up -d wso2is"
echo ""
echo "2. Wait for WSO2 IS to start (about 2-3 minutes)"
echo ""
echo "3. Access WSO2 IS Console:"
echo "   https://wso2.18.143.154.126.nip.io:9443/carbon"
echo "   Username: admin"
echo "   Password: admin"
echo ""
echo "4. Update Service Provider:"
echo "   - Go to Applications > List"
echo "   - Find 'FIDO_POC_App'"
echo "   - Click Edit"
echo "   - Go to FIDO2 tab"
echo "   - Update Relying Party ID: fido.18.143.154.126.nip.io"
echo "   - Update App ID: https://fido.18.143.154.126.nip.io"
echo "   - Update Trusted Origins:"
echo "     - https://fido.18.143.154.126.nip.io"
echo "     - https://wso2.18.143.154.126.nip.io"
echo "   - Save"
echo ""
echo "5. Test the fix:"
echo "   - Access: https://fido.18.143.154.126.nip.io"
echo "   - Try FIDO authentication"
echo "   - Check browser console for rpId value"
echo ""
echo "🎯 Expected result:"
echo "   ✅ rpId should be 'fido.18.143.154.126.nip.io'"
echo "   ✅ No more 'wso2is' rpId in response"
echo "   ✅ WebAuthn authentication should work"
echo ""
echo "📝 Note: This approach:"
echo "   ✅ Keeps your custom WSO2 IS image"
echo "   ✅ Preserves all your localhost data"
echo "   ✅ Only requires updating one configuration"
echo "   ✅ Fixes the rpId issue permanently"


